<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>bringup</name>
  <version>0.0.0</version>
  <description>Puzzlebot master launch files for simulation and real robot</description>
  <maintainer email="jjjau03@gmail.com">jjj</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>rviz2</exec_depend>
  <exec_depend>description</exec_depend>
  <exec_depend>controller</exec_depend>
  <exec_depend>slam</exec_depend>
  <exec_depend>navigation</exec_depend>
  <exec_depend>perception</exec_depend>
  <exec_depend>lifting</exec_depend>
  <exec_depend>mission_control</exec_depend>
  <exec_depend>dashboard</exec_depend>
  <exec_depend>voice_control</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
