track:
  x: 4.85
  y: 3.65
obstacles:
- name: pared_oeste
  x: 2.44
  y: 3.675
  sx: 4.88
  sy: 0.03
  yaw_deg: 0.0
- name: pared_este
  x: 2.44
  y: 0.015
  sx: 4.88
  sy: 0.03
  yaw_deg: 0.0
- name: pared_norte
  x: 4.865
  y: 1.845
  sx: 0.03
  sy: 3.63
  yaw_deg: 0.0
- name: pared_sur_a
  x: 0.015
  y: 0.175
  sx: 0.03
  sy: 0.35
  yaw_deg: 0.0
- name: dock_1_izq
  x: -0.31
  y: 0.335
  sx: 0.62
  sy: 0.03
  yaw_deg: 0.0
- name: dock_1_der
  x: -0.31
  y: 0.735
  sx: 0.62
  sy: 0.03
  yaw_deg: 0.0
- name: dock_1_frente
  x: -0.605
  y: 0.535
  sx: 0.03
  sy: 0.43
  yaw_deg: 0.0
- name: pared_sur_b
  x: 0.015
  y: 0.795
  sx: 0.03
  sy: 0.15
  yaw_deg: 0.0
- name: dock_2_izq
  x: -0.31
  y: 0.855
  sx: 0.62
  sy: 0.03
  yaw_deg: 0.0
- name: dock_2_der
  x: -0.31
  y: 1.255
  sx: 0.62
  sy: 0.03
  yaw_deg: 0.0
- name: dock_2_frente
  x: -0.605
  y: 1.055
  sx: 0.03
  sy: 0.43
  yaw_deg: 0.0
- name: pared_sur_c
  x: 0.015
  y: 1.315
  sx: 0.03
  sy: 0.15
  yaw_deg: 0.0
- name: dock_3_izq
  x: -0.31
  y: 1.375
  sx: 0.62
  sy: 0.03
  yaw_deg: 0.0
- name: dock_3_der
  x: -0.31
  y: 1.775
  sx: 0.62
  sy: 0.03
  yaw_deg: 0.0
- name: dock_3_frente
  x: -0.605
  y: 1.575
  sx: 0.03
  sy: 0.43
  yaw_deg: 0.0
- name: pared_sur_d
  x: 0.015
  y: 2.025
  sx: 0.03
  sy: 0.53
  yaw_deg: 0.0
- name: pared_sur_e
  x: 0.015
  y: 3.39
  sx: 0.03
  sy: 0.6
  yaw_deg: 0.0
- name: rack_C1_1
  x: 2.6972
  y: 2.4183
  sx: 0.3563
  sy: 0.0795
  yaw_deg: 0.0
- name: rack_C1_2
  x: 3.0535
  y: 2.4183
  sx: 0.3563
  sy: 0.0795
  yaw_deg: 0.0
- name: rack_C1_3
  x: 3.4098
  y: 2.4183
  sx: 0.3563
  sy: 0.0795
  yaw_deg: 0.0
- name: rack_C1_4
  x: 2.6972
  y: 2.3388
  sx: 0.3563
  sy: 0.0795
  yaw_deg: 0.0
- name: rack_C1_5
  x: 3.0535
  y: 2.3388
  sx: 0.3563
  sy: 0.0795
  yaw_deg: 0.0
- name: rack_C1_6
  x: 3.4098
  y: 2.3388
  sx: 0.3563
  sy: 0.0795
  yaw_deg: 0.0
- name: rack_C2_1
  x: 2.6802
  y: 1.2942
  sx: 0.3583
  sy: 0.0735
  yaw_deg: 0.0
- name: rack_C2_2
  x: 3.0385
  y: 1.2942
  sx: 0.3583
  sy: 0.0735
  yaw_deg: 0.0
- name: rack_C2_3
  x: 3.3968
  y: 1.2942
  sx: 0.3583
  sy: 0.0735
  yaw_deg: 0.0
- name: rack_C2_4
  x: 2.6802
  y: 1.2207
  sx: 0.3583
  sy: 0.0735
  yaw_deg: 0.0
- name: rack_C2_5
  x: 3.0385
  y: 1.2207
  sx: 0.3583
  sy: 0.0735
  yaw_deg: 0.0
- name: rack_C2_6
  x: 3.3968
  y: 1.2207
  sx: 0.3583
  sy: 0.0735
  yaw_deg: 0.0
- name: rack_B_1
  x: 1.488
  y: 2.1208
  sx: 0.088
  sy: 0.3583
  yaw_deg: 0.0
- name: rack_B_2
  x: 1.576
  y: 2.1208
  sx: 0.088
  sy: 0.3583
  yaw_deg: 0.0
- name: rack_B_3
  x: 1.488
  y: 1.7625
  sx: 0.088
  sy: 0.3583
  yaw_deg: 0.0
- name: rack_B_4
  x: 1.576
  y: 1.7625
  sx: 0.088
  sy: 0.3583
  yaw_deg: 0.0
- name: rack_B_5
  x: 1.488
  y: 1.4042
  sx: 0.088
  sy: 0.3583
  yaw_deg: 0.0
- name: rack_B_6
  x: 1.576
  y: 1.4042
  sx: 0.088
  sy: 0.3583
  yaw_deg: 0.0
- name: roller_R1
  x: 4.675
  y: 1.785
  sx: 0.47
  sy: 0.17
  yaw_deg: 0.0
- name: roller_R2
  x: 4.675
  y: 1.375
  sx: 0.47
  sy: 0.17
  yaw_deg: 0.0
- name: roller_R3
  x: 4.675
  y: 0.955
  sx: 0.47
  sy: 0.19
  yaw_deg: 0.0
- name: roller_R4
  x: 4.675
  y: 0.555
  sx: 0.47
  sy: 0.17
  yaw_deg: 0.0
