track:
  x: 4.85
  y: 3.65
obstacles:
- name: pared_oeste
  x: 2.44
  y: 3.675
  sx: 4.88
  sy: 0.03
  yaw_deg: 0.0
- name: pared_este
  x: 2.44
  y: 0.015
  sx: 4.88
  sy: 0.03
  yaw_deg: 0.0
- name: pared_norte
  x: 4.865
  y: 1.845
  sx: 0.03
  sy: 3.63
  yaw_deg: 0.0
- name: pared_sur_a
  x: 0.015
  y: 0.175
  sx: 0.03
  sy: 0.35
  yaw_deg: 0.0
- name: dock_1_izq
  x: -0.31
  y: 0.335
  sx: 0.62
  sy: 0.03
  yaw_deg: 0.0
- name: dock_1_der
  x: -0.31
  y: 0.735
  sx: 0.62
  sy: 0.03
  yaw_deg: 0.0
- name: dock_1_frente
  x: -0.605
  y: 0.535
  sx: 0.03
  sy: 0.43
  yaw_deg: 0.0
- name: pared_sur_b
  x: 0.015
  y: 0.795
  sx: 0.03
  sy: 0.15
  yaw_deg: 0.0
- name: dock_2_izq
  x: -0.31
  y: 0.855
  sx: 0.62
  sy: 0.03
  yaw_deg: 0.0
- name: dock_2_der
  x: -0.31
  y: 1.255
  sx: 0.62
  sy: 0.03
  yaw_deg: 0.0
- name: dock_2_frente
  x: -0.605
  y: 1.055
  sx: 0.03
  sy: 0.43
  yaw_deg: 0.0
- name: pared_sur_c
  x: 0.015
  y: 1.315
  sx: 0.03
  sy: 0.15
  yaw_deg: 0.0
- name: dock_3_izq
  x: -0.31
  y: 1.375
  sx: 0.62
  sy: 0.03
  yaw_deg: 0.0
- name: dock_3_der
  x: -0.31
  y: 1.775
  sx: 0.62
  sy: 0.03
  yaw_deg: 0.0
- name: dock_3_frente
  x: -0.605
  y: 1.575
  sx: 0.03
  sy: 0.43
  yaw_deg: 0.0
- name: pared_sur_d
  x: 0.015
  y: 2.025
  sx: 0.03
  sy: 0.53
  yaw_deg: 0.0
- name: pared_sur_e
  x: 0.015
  y: 3.39
  sx: 0.03
  sy: 0.6
  yaw_deg: 0.0
- name: rack_A_1
  x: 2.245
  y: 3.585
  sx: 0.35
  sy: 0.15
  yaw_deg: 180.0
- name: rack_A_2
  x: 2.655
  y: 3.585
  sx: 0.35
  sy: 0.15
  yaw_deg: 180.0
- name: rack_A_3
  x: 3.065
  y: 3.585
  sx: 0.35
  sy: 0.15
  yaw_deg: 180.0
- name: rack_B_4
  x: 1.475
  y: 1.425
  sx: 0.35
  sy: 0.15
  yaw_deg: 90.0
- name: rack_B_5
  x: 1.475
  y: 1.775
  sx: 0.35
  sy: 0.15
  yaw_deg: 90.0
- name: rack_B_6
  x: 1.475
  y: 2.125
  sx: 0.35
  sy: 0.15
  yaw_deg: 90.0
- name: rack_B_7
  x: 1.625
  y: 1.425
  sx: 0.35
  sy: 0.15
  yaw_deg: 270.0
- name: rack_B_8
  x: 1.625
  y: 1.775
  sx: 0.35
  sy: 0.15
  yaw_deg: 270.0
- name: rack_B_9
  x: 1.625
  y: 2.125
  sx: 0.35
  sy: 0.15
  yaw_deg: 270.0
- name: rack_C1_10
  x: 2.905
  y: 2.405
  sx: 0.35
  sy: 0.15
  yaw_deg: 180.0
- name: rack_C1_11
  x: 3.255
  y: 2.405
  sx: 0.35
  sy: 0.15
  yaw_deg: 180.0
- name: rack_C1_12
  x: 3.605
  y: 2.405
  sx: 0.35
  sy: 0.15
  yaw_deg: 180.0
- name: rack_C1_13
  x: 2.905
  y: 2.555
  sx: 0.35
  sy: 0.15
  yaw_deg: 0.0
- name: rack_C1_14
  x: 3.255
  y: 2.555
  sx: 0.35
  sy: 0.15
  yaw_deg: 0.0
- name: rack_C1_15
  x: 3.605
  y: 2.555
  sx: 0.35
  sy: 0.15
  yaw_deg: 0.0
- name: rack_C2_16
  x: 2.905
  y: 1.175
  sx: 0.35
  sy: 0.15
  yaw_deg: 180.0
- name: rack_C2_17
  x: 3.255
  y: 1.175
  sx: 0.35
  sy: 0.15
  yaw_deg: 180.0
- name: rack_C2_18
  x: 3.605
  y: 1.175
  sx: 0.35
  sy: 0.15
  yaw_deg: 180.0
- name: rack_C2_19
  x: 2.905
  y: 1.325
  sx: 0.35
  sy: 0.15
  yaw_deg: 0.0
- name: rack_C2_20
  x: 3.255
  y: 1.325
  sx: 0.35
  sy: 0.15
  yaw_deg: 0.0
- name: rack_C2_21
  x: 3.605
  y: 1.325
  sx: 0.35
  sy: 0.15
  yaw_deg: 0.0
- name: rack_D_22
  x: 2.245
  y: 0.105
  sx: 0.35
  sy: 0.15
  yaw_deg: 0.0
- name: rack_D_23
  x: 2.655
  y: 0.105
  sx: 0.35
  sy: 0.15
  yaw_deg: 0.0
- name: roller_R1_1
  x: 4.79
  y: 0.55
  sx: 0.12
  sy: 0.16
  yaw_deg: -90.0
- name: roller_R1_2
  x: 4.67
  y: 0.55
  sx: 0.12
  sy: 0.16
  yaw_deg: -90.0
- name: roller_R1_3
  x: 4.55
  y: 0.55
  sx: 0.12
  sy: 0.16
  yaw_deg: -90.0
- name: roller_R1_4
  x: 4.43
  y: 0.55
  sx: 0.12
  sy: 0.16
  yaw_deg: -90.0
- name: roller_R2_5
  x: 4.79
  y: 0.94
  sx: 0.12
  sy: 0.16
  yaw_deg: -90.0
- name: roller_R2_6
  x: 4.67
  y: 0.94
  sx: 0.12
  sy: 0.16
  yaw_deg: -90.0
- name: roller_R2_7
  x: 4.55
  y: 0.94
  sx: 0.12
  sy: 0.16
  yaw_deg: -90.0
- name: roller_R2_8
  x: 4.43
  y: 0.94
  sx: 0.12
  sy: 0.16
  yaw_deg: -90.0
- name: roller_R3_9
  x: 4.79
  y: 1.33
  sx: 0.12
  sy: 0.16
  yaw_deg: -90.0
- name: roller_R3_10
  x: 4.67
  y: 1.33
  sx: 0.12
  sy: 0.16
  yaw_deg: -90.0
- name: roller_R3_11
  x: 4.55
  y: 1.33
  sx: 0.12
  sy: 0.16
  yaw_deg: -90.0
- name: roller_R3_12
  x: 4.43
  y: 1.33
  sx: 0.12
  sy: 0.16
  yaw_deg: -90.0
- name: roller_R4_13
  x: 4.79
  y: 1.72
  sx: 0.12
  sy: 0.16
  yaw_deg: -90.0
- name: roller_R4_14
  x: 4.67
  y: 1.72
  sx: 0.12
  sy: 0.16
  yaw_deg: -90.0
- name: roller_R4_15
  x: 4.55
  y: 1.72
  sx: 0.12
  sy: 0.16
  yaw_deg: -90.0
- name: roller_R4_16
  x: 4.43
  y: 1.72
  sx: 0.12
  sy: 0.16
  yaw_deg: -90.0
- name: roller_R5_17
  x: 4.63
  y: 3.09
  sx: 0.12
  sy: 0.16
  yaw_deg: 0.0
- name: roller_R5_18
  x: 4.63
  y: 2.97
  sx: 0.12
  sy: 0.16
  yaw_deg: 0.0
- name: roller_R5_19
  x: 4.63
  y: 2.85
  sx: 0.12
  sy: 0.16
  yaw_deg: 0.0
- name: roller_R5_20
  x: 4.63
  y: 2.73
  sx: 0.12
  sy: 0.16
  yaw_deg: 0.0
- name: roller_R5_21
  x: 4.63
  y: 2.61
  sx: 0.12
  sy: 0.16
  yaw_deg: 0.0
