rack_dims:
  largo: 0.35
  prof: 0.15
  z: 0.2
groups:
  A:
  - cx: 2.245
    cy: 3.585
    yaw: 180
  - cx: 2.655
    cy: 3.585
    yaw: 180
  - cx: 3.065
    cy: 3.585
    yaw: 180
  B:
  - cx: 1.475
    cy: 1.425
    yaw: 90
  - cx: 1.475
    cy: 1.775
    yaw: 90
  - cx: 1.475
    cy: 2.125
    yaw: 90
  - cx: 1.625
    cy: 1.425
    yaw: 270
  - cx: 1.625
    cy: 1.775
    yaw: 270
  - cx: 1.625
    cy: 2.125
    yaw: 270
  C1:
  - cx: 2.905
    cy: 2.405
    yaw: 180
  - cx: 3.255
    cy: 2.405
    yaw: 180
  - cx: 3.605
    cy: 2.405
    yaw: 180
  - cx: 2.905
    cy: 2.555
    yaw: 0
  - cx: 3.255
    cy: 2.555
    yaw: 0
  - cx: 3.605
    cy: 2.555
    yaw: 0
  C2:
  - cx: 2.905
    cy: 1.175
    yaw: 180
  - cx: 3.255
    cy: 1.175
    yaw: 180
  - cx: 3.605
    cy: 1.175
    yaw: 180
  - cx: 2.905
    cy: 1.325
    yaw: 0
  - cx: 3.255
    cy: 1.325
    yaw: 0
  - cx: 3.605
    cy: 1.325
    yaw: 0
  D:
  - cx: 2.245
    cy: 0.105
    yaw: 0
  - cx: 2.655
    cy: 0.105
    yaw: 0
